### ISSUE TITLE
Data models 

### ISSUE THREAD

**Issue by jtkaufman737** [jtkaufman737/project_generator_api#1]
So at first I was thinking "this could be a really simple data model" and then almost immediately I reversed myself (lol). 

What I came up with in terms of entity relationships would be something like **one project** can have **one or many** languages, **one language** can have **many frameworks**...so that makes our entities Project, Language, Framework. 

In terms of other data, I thought that languages would have a flag for frontend or backend so that they could get appropriately selected - like if someone picks a command line application or an API, they won't need HTML or CSS or a frontend JS framework. 

HTML and CSS is kind of an interesting edge case, or maybe just HTML. Even if we wanted our project to use React or Vue or <whatever> it could be reasonably assumed everything will use HTML if it has a frontend. The same is true of CSS, except that I would probably also like CSS frameworks to be selectable (Tailwinds, Bootstrap, Bulma etc). So I guess what that means for the data relationship is that a project can have multiple languages and multiple frameworks.

_A mishmash of other thoughts:_ 
- Project types: a field on the Project model...could include command line, mobile, API, full stack, or database-less (is there a better word for that lol?)...if I'm missing any please chime in 
- Project subject...lets crowdsource these from code buddies! A few I have off the bat: project clones (that's a whole genre we could elaborate on - 'recreate Trello/Netflix/etc', recreate popular games (War, Hearts, Poker, Candy Crush, etc), an app to tell whether you are hungry or bored, text based roleplaying games, various types of tracking applications (track your run, track your budget, etc), someone the other day was saying they wanted like a project/language tree to figure out what programming languages & frameworks are related to each other 
- Project name...I guess we'll let people select their own so we don't need to worry about this, but maybe let people author it on API entries(?) 

I'm sure more will come to mind but please don't hesitate to share any thoughts you have so far!

**Comment by angelocordon** [comment]
It would be also great if we can also display with projects:

Difficulty levels,
Estimated time it should take

**Comment by angelocordon** [comment]
The frameworks question is interesting — I suppose it’s an additional challenge to tell people to go build this in X - on the other hand, I wonder if most people already know what they’re comfortable with and just need a project spec generator?

I’m thinking of it from the payload perspective as:

{
  short_description: “serverless budget tracker”,
  long_description: “build a budget tracker that tracks your incoming money and outgoing using serverless methodologies; must include categories for spending and income.”,
  difficulty: “medium”,
  duration: “1 - 2 days”,
  technology_tags: [“serverless”, “next”, “lambda”]
}

The idea challenge is to build it as a serverless app, but anybody can use whatever framework they want to achieve it. The tags might be interesting should they chose to want to build it in a specific framework. 

Additionally there, what if they don’t want to build it serverless and just build a budget tracker? I’m wondering if the simplest way would be to build an API that returns project ideas and specs but be fooling agnostic.

**Comment by jtkaufman737** [comment]
Hm so the reason I was thinking of it that way was I guess in the context of the original discussion - "I know PHP and Java and am looking for a project to do." 

I think this idea has advantages in being more open ended, but a disadvantage in that it involved a lot more reponsibility for content creation on the side of the people making api entries, whereas "serverless budget tracker with aws lambda" is more open ended in scope. They could kind of add what features they have the time and capability to add. 

I _like_ the idea of difficulty recommendations but I could also see that being really subjective. Like if we need to make a recommendation on difficulty level for say, a PHP/Drupal project with an Angular frontend - none of us know that, so to develop an estimate we are kind of at the mercy for whoever is around code buddies to guesstimate the difficulty level. 

Want to throw it to a vote? I'm open to going in either direction, I can see pros and cons to both options. I can set it up as a poll in that slack channel.

**Comment by angelocordon** [comment]
Your ideas make sense!

**Comment by stain88** [comment]
Just gonna leave here what I mentioned in slack:

Instead of _difficulty recommendations_, we could focus on duration, but without specifying an actual length of time. For example, whatever language you choose to use, or however comfortable you might be, a basic calculator app would probably be deemed "short" compared to a full facebook clone

**Comment by jtkaufman737** [comment]
Honestly what would be really great would be a user defined feedback field on both duration and difficulty 🧐

**Comment by jtkaufman737** [comment]
Like an automated “please review project x”’ would solicit it if someone marked that they completed the project but that kind of changes the implementation idea of the whole project a bit

**Comment by angelocordon** [comment]
That might be better in v2 :)

**Comment by jtkaufman737** [comment]
Before closing this out I'll provide an update that the final format we landed on for the data models was 

**Project**
- Name
- Type (API, Frontend, Backend, Command Line, Full Stack, Progressive Web App, Mobile App )
- ID (primary key not null)
- Project details/description
- Has js framework
- javascript framework ID (foreign key) 
- Has css framework
- CSS framework ID (foreign key)
- Has database
- database id (foreign key)
- Has server side lang
- server side language ID (foreign key)
- Has wildcard
- Wildcard ID (foreign key)

**Language**
- Name (not null)
- ID (Primary key not null)

**Framework/Platform**
- Framework ID (primary key not null)
- Name
- Type (DB/CSS/JS/Server side)
- Lang ID (foreign key not null)

**Wildcard**
- ID (primary key not null)
- Title
- Description
